### PR TITLE
add app icons and custom tab bar height

### PR DESCRIPTION
**Pull request by MattHuie**
I added the app icons and a custom tab bar height

### CODE REVIEW

**Comment by vhart** [comment]
@MattHuie would you mind including a simulator screenshot?

**Comment by MattHuie** [comment]
Simulator Screen Shot - iPhone 7 Plus - 2019-04-30 at 11 27 38

**Review by vhart — APPROVED** [review]
LGTM Nice improvement

**Comment by vhart** [comment]
@MattHuie why is this the old purple layout? I though the collection view was updated

**Comment by MattHuie** [comment]
We dont have ramu's part merged with the dev-branch yet
which is why its still purple with horrible layout

**Pull request merged**
